// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/dashboard

package dashboard

import "github.com/perses/spec/cue/common"

#Display: {
	name:         string @go(Name)
	description?: string @go(Description)
	hidden?:      bool   @go(Hidden)
	color?:       string @go(Color)
}

#AnnotationSpec: {
	display: #Display       @go(Display)
	plugin:  common.#Plugin @go(Plugin)
}
